-- MySQL Script generated by MySQL Workbench
-- 10/12/16 12:04:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema schedule_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema schedule_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `schedule_db` DEFAULT CHARACTER SET utf8 ;
USE `schedule_db` ;

-- -----------------------------------------------------
-- Table `schedule_db`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schedule_db`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `e-mail` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUsers_UNIQUE` (`idUser` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schedule_db`.`Schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schedule_db`.`Schedule` (
  `idSchedule` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `days` INT NOT NULL,
  PRIMARY KEY (`idSchedule`),
  UNIQUE INDEX `idSchedules_UNIQUE` (`idSchedule` ASC),
  INDEX `idUser_idx` (`idUser` ASC),
  CONSTRAINT `idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `schedule_db`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schedule_db`.`Object`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schedule_db`.`Object` (
  `idObject` INT NOT NULL AUTO_INCREMENT,
  `idSchedule` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `count` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idObject`),
  UNIQUE INDEX `idObjects_UNIQUE` (`idObject` ASC),
  INDEX `idSchedule_idx` (`idSchedule` ASC),
  CONSTRAINT `idSchedule`
    FOREIGN KEY (`idSchedule`)
    REFERENCES `schedule_db`.`Schedule` (`idSchedule`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schedule_db`.`Parameter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schedule_db`.`Parameter` (
  `idParameter` INT NOT NULL AUTO_INCREMENT,
  `idObject` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idParameter`),
  UNIQUE INDEX `idParameters_UNIQUE` (`idParameter` ASC),
  INDEX `idObject_idx` (`idObject` ASC),
  CONSTRAINT `idObject`
    FOREIGN KEY (`idObject`)
    REFERENCES `schedule_db`.`Object` (`idObject`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
